name: "Update Upstream"

on:
  schedule:
    - cron: "5 4 * * *"
  workflow_dispatch:

permissions:
  id-token: write
  attestations: write

jobs:
  build:
    uses: wasilibs/actions/.github/workflows/update.yaml@ea2bfc14aa6243219a25293ee36e85a098039303
    secrets: inherit
